create table person_roles
(
    id        integer generated by default as identity
        primary key,
    person_id integer   not null
        references person,
    role_id   integer   not null
        references roles,
    from_date timestamp not null,
    by_date   timestamp not null
);

alter table person_roles
    owner to postgres;

INSERT INTO public.person_roles (id, person_id, role_id, from_date, by_date) VALUES (4, 3, 1, '2020-12-22 00:00:00.000000', '2022-12-10 00:00:00.000000');
INSERT INTO public.person_roles (id, person_id, role_id, from_date, by_date) VALUES (5, 4, 2, '2020-12-22 00:00:00.000000', '2022-12-10 00:00:00.000000');
INSERT INTO public.person_roles (id, person_id, role_id, from_date, by_date) VALUES (6, 3, 2, '2020-12-22 00:00:00.000000', '2022-12-11 00:00:00.000000');
INSERT INTO public.person_roles (id, person_id, role_id, from_date, by_date) VALUES (7, 5, 3, '2022-12-10 17:42:22.000000', '2022-12-24 17:42:26.000000');
INSERT INTO public.person_roles (id, person_id, role_id, from_date, by_date) VALUES (8, 5, 1, '2022-12-11 17:43:34.000000', '2022-12-26 17:43:35.000000');
