create table roles
(
    id             integer generated by default as identity
        primary key,
    name           varchar(25) not null,
    authorities_id integer
        references authorities
);

alter table roles
    owner to postgres;

INSERT INTO public.roles (id, name, authorities_id) VALUES (1, 'admin', 1);
INSERT INTO public.roles (id, name, authorities_id) VALUES (2, 'user', 2);
INSERT INTO public.roles (id, name, authorities_id) VALUES (3, 'editor', 3);
