create table roles
(
    id   integer generated by default as identity
        primary key,
    name varchar(25) not null
);

alter table roles
    owner to postgres;

INSERT INTO public.roles (id, name) VALUES (1, 'admin');
INSERT INTO public.roles (id, name) VALUES (2, 'user');
INSERT INTO public.roles (id, name) VALUES (3, 'editor');
